#!/usr/bin/env zsh

for p ($path) {
  if [[ -d "$p" ]]; then
    # if symlink
    if [[ -L "$p" ]]; then
      local target=$(readlink "$p")
      ls -1 "$p" | sed "s/^/${p//\//\\/}\//" | sed "s/\$/ -> ${target//\//\\/}/"
    else
      ls -1 "$p" | sed "s/^/${p//\//\\/}\//"
    fi
  fi
}
