#!/bin/zsh

start-commands() {
    tmux send-keys -t faith:1.1 $'sru 1; sstatus; rs\n'         # faith rails
    tmux send-keys -t faith:2.1 $'sru 1; sstatus; rs -p 3001\n' # fake_rsql rails
    tmux send-keys -t baton:1.1 $'Sru 1; Sstatus\n'              # baton rails
    tmux send-keys -t notab:1.1 $'Sru 1; Sstatus\n'              # notab rails
}

# ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh

tall

start-commands
