#!/usr/bin/env zsh

mkdir -p ~/.pyenv/versions
ln -nfs /usr/local/Cellar/python@2/2*(On[1]) ~/.pyenv/versions/
ln -nfs /usr/local/Cellar/python@2/2*(On[1]) ~/.pyenv/versions/2
ln -nfs /usr/local/Cellar/python@3.10/3*(On[1]) ~/.pyenv/versions/
ln -nfs /usr/local/Cellar/python@3.10/3*(On[1]) ~/.pyenv/versions/3
ln -nfs /usr/local/Cellar/python@3.10/3*(On[1]) ~/.pyenv/versions/3.10
ln -nfs /usr/local/Cellar/python@3.9/3*(On[1]) ~/.pyenv/versions/3.9
ln -nfs /usr/local/Cellar/python@3.8/3*(On[1]) ~/.pyenv/versions/3.8
cd ~/.pyenv/versions/3/bin
cp -Rf python3 python
cp -Rf pip3 pip
cd ~/.pyenv/versions/3.9/bin
cp -Rf python3.9 python3
cp -Rf python3.9 python
cp -Rf pip3.9 pip3
cp -Rf pip3.9 pip
cd ~/.pyenv/versions/3.8/bin
cp -Rf python3.8 python3
cp -Rf python3.8 python
cp -Rf pip3.8 pip3
cp -Rf pip3.8 pip

echo 'pyenv versions updated.'

###################################################################

brew unlink node && brew link --overwrite node@14
echo 'node unlinked and node@14 linked'


###################################################################
ln -nfs /usr/local/Cellar/plantuml/*/libexec/plantuml.jar /usr/local/libexec/plantuml.jar
echo 'plantuml link updated.'

sudo rm -rf /Applications/Microsoft\ Edge.app/Contents/Resources/zh_*.lproj
echo 'Microsoft Edge zh_CN, zh_TW removed.'
