#!/usr/bin/env zsh


if [ -z "$HOMEBREW_PREFIX" ]; then
  if [ -e "/opt/homebrew/bin/brew" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
fi


###################################################################
mkdir -p $HOMEBREW_PREFIX/libexec
ln -nfs $HOMEBREW_PREFIX/Cellar/plantuml/*/libexec/plantuml.jar $HOMEBREW_PREFIX/libexec/plantuml.jar
echo "\nplantuml link updated."
ls -l $HOMEBREW_PREFIX/libexec/plantuml.jar | sed 's/^/  /'

# if [ -e /Applications/Microsoft\ Edge.app/Contents/Resources/zh_CN.lproj ]; then
#   sudo rm -rf /Applications/Microsoft\ Edge.app/Contents/Resources/zh_*.lproj
#   echo "\nMicrosoft Edge zh_CN, zh_TW removed."
# fi
