#!/usr/bin/env zsh

if [ -z "$HOMEBREW_PREFIX" ]; then
  if [ -e "/opt/homebrew/bin/brew" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
fi

mkdir -p ~/.pyenv/versions

if [ -e "$HOMEBREW_PREFIX/Cellar/python@2" ]; then
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@2/2*(On[1]) ~/.pyenv/versions/
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@2/2*(On[1]) ~/.pyenv/versions/2
fi

if [ -e "$HOMEBREW_PREFIX/Cellar/python@3.12" ]; then
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.12/3*(On[1]) ~/.pyenv/versions/
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.12/3*(On[1]) ~/.pyenv/versions/3
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.12/3*(On[1]) ~/.pyenv/versions/3.12
fi

if [ -e "$HOMEBREW_PREFIX/Cellar/python@3.11" ]; then
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.11/3*(On[1]) ~/.pyenv/versions/3.11
fi

if [ -e "$HOMEBREW_PREFIX/Cellar/python@3.10" ]; then
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.10/3*(On[1]) ~/.pyenv/versions/3.10
fi


if [ -e "$HOMEBREW_PREFIX/Cellar/python@3.9" ]; then
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.9/3*(On[1]) ~/.pyenv/versions/3.9
fi

if [ -e "$HOMEBREW_PREFIX/Cellar/python@3.8" ]; then
  ln -nfs $HOMEBREW_PREFIX/Cellar/python@3.8/3*(On[1]) ~/.pyenv/versions/3.8
fi

cd ~/.pyenv/versions/3/bin
cp -Rf python3.12 python3
cp -Rf python3 python
cp -Rf pip3.12 pip3
cp -Rf pip3 pip
cp -Rf pydoc3.12 pydoc3
cp -Rf python3.12-config python3-config
cp -Rf 2to3-3.12 2to3
cp -Rf idle3.12 idle3
ln -nfs wheel3.12 wheel3

if [ -e ~/.pyenv/versions/3.11 ]; then
  cd ~/.pyenv/versions/3.11/bin
  cp -Rf python3.11 python3
  cp -Rf python3 python
  cp -Rf pip3.11 pip3
  cp -Rf pip3 pip
  cp -Rf pydoc3.11 pydoc3
  cp -Rf python3.11-config python3-config
  cp -Rf 2to3-3.11 2to3
  cp -Rf idle3.11 idle3
  ln -nfs wheel3.11 wheel3
fi

if [ -e ~/.pyenv/versions/3.10 ]; then
  cd ~/.pyenv/versions/3.10/bin
  cp -Rf python3.10 python3
  cp -Rf python3 python
  cp -Rf pip3.10 pip3
  cp -Rf pip3 pip
fi

if [ -e ~/.pyenv/versions/3.9 ]; then
  cd ~/.pyenv/versions/3.9/bin
  cp -Rf python3.9 python3
  cp -Rf python3.9 python
  cp -Rf pip3.9 pip3
  cp -Rf pip3.9 pip
fi

if [ -e ~/.pyenv/versions/3.8 ]; then
  cd ~/.pyenv/versions/3.8/bin
  cp -Rf python3.8 python3
  cp -Rf python3.8 python
  cp -Rf pip3.8 pip3
  cp -Rf pip3.8 pip
fi

echo 'pyenv versions updated.'
ls -l ~/.pyenv/versions | sed 's/^/  /'

###################################################################
mkdir -p $HOMEBREW_PREFIX/libexec
ln -nfs $HOMEBREW_PREFIX/Cellar/plantuml/*/libexec/plantuml.jar $HOMEBREW_PREFIX/libexec/plantuml.jar
echo "\nplantuml link updated."
ls -l $HOMEBREW_PREFIX/libexec/plantuml.jar | sed 's/^/  /'

# if [ -e /Applications/Microsoft\ Edge.app/Contents/Resources/zh_CN.lproj ]; then
#   sudo rm -rf /Applications/Microsoft\ Edge.app/Contents/Resources/zh_*.lproj
#   echo "\nMicrosoft Edge zh_CN, zh_TW removed."
# fi
