#!/bin/bash

if [ "$(uname)" = Darwin ]; then
  if [ "$(is_inside_emacs)" = true ]; then
    emacsclient --eval "(split-window)" &> /dev/null
    emacsclient "$@"
  else
    emacsclient -s term -t "$@"
  fi
else
  emacsclient -t "$@"
fi
