#!/bin/bash

if [ "$(uname)" = Darwin ]; then
  if [ -n "$INSIDE_EMACS" ]; then
    emacsclient --eval "(other-window 1)" &> /dev/null
    emacsclient "$@"
  else
    emacsclient -s term -t "$@"
  fi
else
  emacsclient -t "$@"
fi
