#!/bin/bash

file_path=$1
if echo "$file_path" | grep -qF 'src.zip!'; then
    file_path=/Users/liuxiang/cascode/java/java-sources$(echo "$file_path" | perl -pe 's#.*src\.zip!##')
fi

/usr/local/bin/emacsclient -n "$file_path"
