#!/bin/bash

if [ -n "$2" ]; then
  file=$2
else
  file=$1
fi

if [ "$(uname)" = Darwin ]; then
  if [ "$USER" = "root" ]; then
    sudo -u liuxiang emacsclient --eval "(split-window)" &> /dev/null
    sudo -u liuxiang emacsclient "/sudo:root@localhost:$file"
  else
    emacsclient --eval "(split-window)" &> /dev/null
    emacsclient "$@"
  fi
else
  emacsclient -t "$@"
fi
