#!/bin/bash

copied_path=$(pbpaste)

if [ -n "$copied_path" -a -e "$copied_path" ]; then
    echo -n | pbcopy
    dir=$(dirname "$copied_path")
    cd "$dir"
fi
exec bash -c "fzf --bind 'enter:become:cursor {1}'; exit 0"
