#!/bin/bash

fd | fzf \
    --bind 'enter:become:buddy {}' \
    --bind 'alt-a:reload:fd -u' \
    --bind 'alt-h:reload:fd' \
    --header $'Enter: Open,\t Alt-a: Show All,\t Alt-h: Hide Hidden Files'

exit 0
