#!/bin/bash

if [ -n "$1" ]; then
  remote="$1"
  git fetch "$remote"
  git for-each-ref --sort=-committerdate refs/remotes/"$remote" --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
else
  git_root="$(git rev-parse --show-toplevel)"
  remote_refs_dir="$git_root/.git/refs/remotes"
  for remote in "$remote_refs_dir"/*; do
    remote="$(basename "$remote")"
    git fetch "$remote"
    git for-each-ref --sort=-committerdate refs/remotes/"$remote" --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
  done
fi



