#!/usr/bin/env zsh

for i (*) {
    if [ -d "$i" -a -d "$i/.git" ]; then
      if [ -n "$1" ]; then
        echo -e "


  ===================== $i =====================
  "; (cd "$i"; git branch -vv )
      else
        (cd "$i";
           echo -e "


  ===================== $i =====================
  "; git branch -vv
        )
      fi
    fi
  }
