#!/usr/bin/env zsh

title=$1
[ -n "$title" ] && date=$(date '+%F')
link=$2
[ -n "$link" ] && include_before="LINK: $link"

filter() {
  perl -ne '
    s/\[\[[^\[\]]*\]\[\]\]//g;
    print unless $. == 2;
  '
}

pandoc -s -f html -t org -M title="$title" -M date="$date" -M include-before="$include_before" --wrap=none | filter
