#!/usr/bin/env zsh

title=$1
[ -n "$title" ] && date=$(date '+%F')
link=$2
[ -n "$link" ] && include_before="LINK: $link"

filter() {
  perl -ne '
    s#\[\[(https?://[^\]]+)\]\[{1,4}\1\]{1,4}\]#[[$1]]#g;
    s#\[\[[^\[\]]*\]\[\]\]##g;
    print unless $. == 2 && /^\s*$/;
  '
}

pandoc -s -f html -t org -M title="$title" -M date="$date" -M include-before="$include_before" --wrap=none | filter
