#!/bin/bash


if [ -z "$HOMEBREW_PREFIX" ]; then
  if [ -e "/opt/homebrew/bin/brew" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
fi


export K9SCONFIG=$HOME/.k9s
export LC_CTYPE=en_US.UTF-8
exec $HOMEBREW_PREFIX/bin/k9s "$@"
