#!/bin/zsh

if ! git status &> /dev/null; then
   echo Not a git repository.
   exit 1
fi

if [ "$(uname)" = Darwin ]; then
    emacsclient -t -s term -e "(let ((magit-display-buffer-function #'(lambda (buffer) (display-buffer buffer '(display-buffer-same-window))))) (magit-status \"$(git rev-parse --show-toplevel)\"))"
else
    emacsclient -t -e "(let ((magit-display-buffer-function #'(lambda (buffer) (display-buffer buffer '(display-buffer-same-window))))) (magit-status \"$(git rev-parse --show-toplevel)\"))"
fi
