#!/usr/bin/env zsh

if ! git status &> /dev/null; then
   echo Not a git repository.
   exit 1
fi

nvim -c '
  execute "autocmd User NeogitStatusRefreshed lua map_q_for_neogit()"
  execute "Neogit"
'

# if [ "$(uname)" = Darwin ]; then
#     emacsclient -t -s term -e "(let ((magit-display-buffer-function #'(lambda (buffer) (display-buffer buffer '(display-buffer-same-window))))) (magit-status \"$(git rev-parse --show-toplevel)\"))"
# else
#     emacsclient -t -e "(let ((magit-display-buffer-function #'(lambda (buffer) (display-buffer buffer '(display-buffer-same-window))))) (magit-status \"$(git rev-parse --show-toplevel)\"))"
# fi
