#!/usr/bin/env zsh

if ! git status &> /dev/null; then
   echo Not a git repository.
   exit 1
fi

emacsclient -e "(let ((magit-display-buffer-function #'(lambda (buffer) (display-buffer buffer '(display-buffer-same-window))))) (magit-status \"$(git rev-parse --show-toplevel)\"))"
