#!/usr/bin/env ruby

require "active_support/core_ext/string/inflections"

while line = gets
    puts line.pluralize
end

__END__
#!/usr/bin/perl

use warnings;
use strict;
use utf8;
use Lingua::EN::Inflect qw(PL classical);
# classical(1);
while (<>) {
    chomp;
    print PL($_), "\n";
}
