#!/bin/bash

java_class_file=$1
server=jicai.dev
server_dir=/data/logs/tuan-dev
docker_container=tuan-biz-dev
docker_container_dir=/data/logs/tuan
java_pid=1

base_class_name=$(basename "$java_class_file" .class)

echo -n "Getting Class Loader Hash ..."
class_loader_hash=$(ssh $server "docker exec $docker_container as.sh -c 'sc -d *$base_class_name' $java_pid 2>&1 | awk '/classLoaderHash/{print \$2}' | head -1")
echo -e "\rClass Loader Hash: $class_loader_hash"

echo -n "Copying Class File ..."
rsync -z "$java_class_file" "$server:$server_dir/"
echo -e "\rCopying Class File to $server:$server_dir/$base_class_name.class Done"

echo "Reloading Class ..."
ssh $server "docker exec $docker_container as.sh -c 'redefine -c $class_loader_hash $docker_container_dir/$base_class_name.class' $java_pid"
echo "Reloading Class Done"

echo -n "Cleaning up Class File ..."
ssh $server "rm $server_dir/$base_class_name.class"
echo -e "\rCleaning up Class File Done"

