#!/bin/bash

pattern=$1
file_limit=''
if [ -n "$2" ]; then
    file_limit="-g '$2'"
fi


# RELOAD='reload:rg $file_limit --column --color=always --smart-case {q} || :'
RELOAD="reload:rg $file_limit --column --color=always --smart-case \$(echo {q}) || :"
OPENER='buddy -g {1}:{2}'
fzf --disabled --ansi --multi \
    --bind "start:$RELOAD" --bind "change:$RELOAD" \
    --bind "enter:become:$OPENER" \
    --bind "ctrl-o:execute:$OPENER" \
    --bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
    --delimiter : \
    --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
    --preview-window '~4,+{2}+4/3,<80(up)' \
    --query "$pattern"
exit 0
