#!/bin/bash

# RELOAD='reload:rg --column --color=always --smart-case {q} || :'
RELOAD='reload:rg --column --color=always --smart-case $(echo {q}) || :'
OPENER='cursor -g {1}:{2}'
fzf --disabled --ansi --multi \
    --bind "start:$RELOAD" --bind "change:$RELOAD" \
    --bind "enter:become:$OPENER" \
    --bind "ctrl-o:execute:$OPENER" \
    --bind 'alt-a:select-all,alt-d:deselect-all,ctrl-/:toggle-preview' \
    --delimiter : \
    --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
    --preview-window '~4,+{2}+4/3,<80(up)' \
    --query ''
exit 0
