#!/usr/bin/env zsh

ruby_dir=$(print $HOME/.rvm/gems/ruby-<0-9>.<0-9>.<0-9>(On[0,1]))
gem_dir=$(print $ruby_dir/gems/rubocop-<0-9>*(On[0,1]))
args=($@)
if [[ $# == 8 && -z "$args[$#]" ]]; then
  args[$#]='stdin'
fi
$gem_dir/exe/rubocop "${args[@]}"
