#!/bin/bash

if [ -n "$INSIDE_EMACS" ]; then
    emacsclient -q --eval "(other-window 1)" &> /dev/null
fi

if [ $(uname) = Darwin ]; then
  open -a Emacs
  OPTS='-n'
else
  OPTS='-t'
fi

if [ -n "$1" ]; then
    typeset -a files=()
    for arg in "$@"; do
        files+=("/sudo:root@localhost:$(cd $(dirname $arg); echo "$(pwd)/$(basename $arg)")")
    done
    emacsclient "$OPTS" "${files[@]}"
else
    emacsclient "$OPTS" "/sudo:root@localhost:$PWD"
fi

