#!/bin/bash

url="http://$(ifconfig en0 | ag '(?<=inet )\S+' -o):${1:-8080}/"
echo "$url" | pbcopy
echo "URL copied to clipboard: $url"
echo '---------------------------------------'
echo
python -m SimpleHTTPServer ${1:-8080}
# ruby -run -e httpd . -p ${1:-8080}
