#!/usr/bin/env zsh

if [ -z "$HOMEBREW_PREFIX" ]; then
  if [ -e "/opt/homebrew/bin/brew" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
fi

find $HOMEBREW_PREFIX/Cellar -name 'homebrew.mxcl.*.plist' -exec cp {} ~/.config/services/ \;
