#!/bin/bash


if [ "$1" = 8 -o "$1" = 1.8 ]; then
  java_dir=$(echo /Library/Java/JavaVirtualMachines/jdk*1.8*.jdk)
else
  java_dir=$(echo /Library/Java/JavaVirtualMachines/jdk*$1*.jdk)
fi

if [ -e "$java_dir" ]; then
  cd /Library/Java/JavaVirtualMachines
  for version in *; do
    if [ "$version" != CurrentJDK ]; then
      if [ -e "$version"/Contents/Info.plist  ]; then
        mv "$version"/Contents/Info.plist "$version"/Contents/Info.plist.disabled
      fi
    fi
  done

  ln -nfs "$java_dir" /Library/Java/JavaVirtualMachines/CurrentJDK
  mv "$java_dir"/Contents/Info.plist.disabled "$java_dir"/Contents/Info.plist
  /usr/bin/java -version
else
  echo "Version not found: $1"
  ls -l /Library/Java/JavaVirtualMachines/
  exit 1
fi


