#!/usr/bin/env zsh

name=$1

config_file=$HOME/.vrl.yml

function view_remote_log() {
  local config_name=$1
  local auto=$2

  ssh=$(yq e ".$config_name.ssh" "$config_file")
  file=$(yq e ".$config_name.file" "$config_file")
  file_type=$(ssh $ssh "file $file")
  if echo "$file_type" | grep -q ': directory$'; then
    shift
    auto=$1
    if [ "$auto" = "-a" ]; then
      selected_file=$(ssh $ssh "ls -t $file/*.log | grep -v gc" | head -1)
      if [ -z "$selected_file" ]; then
        selected_file=$(ssh $ssh "ls -t $file/*" | head -1)
      fi
      selected_file=${selected_file:t}
      file=$(echo ${(q)file}${^${(q)selected_file}})
    else
      selected_file=$(ssh $ssh "find $file -type f -exec ls -lht {} +" | fzf)
      if [ -z "$selected_file" ]; then
        exit 0
      fi
      file=$(echo "$selected_file" | perl -lne 'my @f = split(/\s+/, $_, 9); print $f[8];')
    fi

    if [ -z "$selected_file" ]; then
      exit 0
    fi
  fi

  if [ -n "$TMUX" ]; then
    old_twindow_name=$(tmux display-message -p '#{window_name}')
    tmux rename-window "VRL[$ssh]"
  fi

  ssh $ssh -t "lnav $file"
  # lnav "$ssh:$file"
}

if [ ! -e "$config_file" ]; then
  echo "Config file ($config_file) not found."
  exit 1
fi

names=$(grep '^[^ ]' "$config_file" | sed 's/:$//')

if [ -n "$name" ]; then
  matched_name=$(echo "$names" | grep "$name" | head -1)
  if [ -n "$matched_name" ]; then
    view_remote_log "$matched_name" "$2"
  else
    echo "Config item named ($name) not found"
    exit 1
  fi
else
  selected_name=$(echo "$names" | fzf --bind='enter:accept,alt-enter:execute(echo auto)+accept')
  if [ -z "$selected_name" ]; then
    exit
  fi

  if echo "$selected_name" | head -1 | grep -q "^auto$"; then
    selected_name=$(echo "$selected_name" | tail -1)
    view_remote_log "$selected_name"
  else
    view_remote_log "$selected_name" -a
  fi
fi
